/**
 * Seed de recetas iniciales para HU-06.
 *
 * Distribución objetivo (~50):
 *   - 12 colombianas (CO)
 *   - 8 latinoamericanas (MX, AR, PE, VE)
 *   - 10 internacionales saludables
 *   - 12 desayunos rápidos
 *   - 10 cenas ligeras / snacks
 *
 * Cada receta lleva:
 *   - prep + cook en minutos (real, sin embellecer)
 *   - costLevel realista
 *   - dietTags / allergyTags exhaustivos
 *   - Macros estimadas por serving (denormalizadas)
 *
 * Los ingredientes se especifican como `ingredientHints[]` con nombre
 * aproximado del Food → el script de seed los matchea por nombre contra
 * DB. Si no encuentra, ese ingrediente se omite del Recipe (no rompe).
 */

export type RecipeSeed = {
  name: string;
  description?: string;
  instructions: string;
  prepTimeMin: number;
  cookTimeMin: number;
  servings: number;
  dietTags: string[];
  allergyTags: string[];
  costLevel: 1 | 2 | 3;
  cuisineCode: string | null;
  caloriesPerServing: number;
  proteinPerServing: number;
  carbsPerServing: number;
  fatPerServing: number;
  ingredientHints: { hint: string; gramsPerServing: number; optional?: boolean }[];
};

export const RECIPES_SEED: RecipeSeed[] = [
  // ─── COLOMBIANAS (CO) ────────────────────────────────────────────
  {
    name: "Arepa con huevo revuelto",
    description: "Desayuno colombiano clásico: arepa de maíz con huevos.",
    instructions:
      "1. Calentar la arepa en sartén o plancha.\n2. Revolver 2 huevos con sal.\n3. Servir caliente.",
    prepTimeMin: 5,
    cookTimeMin: 10,
    servings: 1,
    dietTags: ["vegetariano", "sin-gluten"],
    allergyTags: ["huevo"],
    costLevel: 1,
    cuisineCode: "CO",
    caloriesPerServing: 360,
    proteinPerServing: 18,
    carbsPerServing: 35,
    fatPerServing: 14,
    ingredientHints: [
      { hint: "Arepa de maíz blanco", gramsPerServing: 60 },
      { hint: "Huevo", gramsPerServing: 100 },
    ],
  },
  {
    name: "Bandeja paisa (porción reducida)",
    description: "Versión reducida en porciones del plato típico paisa.",
    instructions:
      "1. Cocinar fríjoles paisas previamente.\n2. Hacer arroz blanco.\n3. Freír huevo, plátano y carne molida.\n4. Servir todo en un plato grande.",
    prepTimeMin: 15,
    cookTimeMin: 30,
    servings: 1,
    dietTags: [],
    allergyTags: ["huevo"],
    costLevel: 2,
    cuisineCode: "CO",
    caloriesPerServing: 780,
    proteinPerServing: 45,
    carbsPerServing: 70,
    fatPerServing: 32,
    ingredientHints: [
      { hint: "Fríjoles paisas", gramsPerServing: 120 },
      { hint: "Arroz", gramsPerServing: 80 },
      { hint: "Plátano maduro frito", gramsPerServing: 60 },
      { hint: "Huevo", gramsPerServing: 50 },
      { hint: "Carne molida", gramsPerServing: 80 },
    ],
  },
  {
    name: "Ajiaco santafereño",
    description: "Sopa bogotana con pollo, papas criollas y guascas.",
    instructions:
      "1. Cocer pollo con cebolla y ajo.\n2. Agregar 3 tipos de papa.\n3. Añadir guascas al final.\n4. Servir con crema y alcaparras.",
    prepTimeMin: 15,
    cookTimeMin: 45,
    servings: 2,
    dietTags: ["sin-gluten"],
    allergyTags: ["lacteos"],
    costLevel: 2,
    cuisineCode: "CO",
    caloriesPerServing: 380,
    proteinPerServing: 30,
    carbsPerServing: 35,
    fatPerServing: 12,
    ingredientHints: [
      { hint: "Pollo", gramsPerServing: 150 },
      { hint: "Papa criolla", gramsPerServing: 120 },
    ],
  },
  {
    name: "Sancocho de gallina",
    description: "Sopa robusta con yuca, plátano, mazorca.",
    instructions:
      "1. Cocer gallina con cilantro.\n2. Agregar yuca, plátano verde, mazorca.\n3. Cocinar 40 min más.",
    prepTimeMin: 20,
    cookTimeMin: 60,
    servings: 3,
    dietTags: ["sin-gluten"],
    allergyTags: [],
    costLevel: 2,
    cuisineCode: "CO",
    caloriesPerServing: 420,
    proteinPerServing: 32,
    carbsPerServing: 40,
    fatPerServing: 14,
    ingredientHints: [
      { hint: "Pollo entero cocido", gramsPerServing: 150 },
      { hint: "Yuca", gramsPerServing: 100 },
    ],
  },
  {
    name: "Sudado de pollo",
    description: "Pollo en salsa criolla con papa, fácil y económico.",
    instructions:
      "1. Sofreír cebolla, tomate, ajo.\n2. Agregar pollo en piezas.\n3. Añadir papa y caldo, cocer 30 min.",
    prepTimeMin: 10,
    cookTimeMin: 40,
    servings: 2,
    dietTags: ["sin-gluten"],
    allergyTags: [],
    costLevel: 1,
    cuisineCode: "CO",
    caloriesPerServing: 410,
    proteinPerServing: 38,
    carbsPerServing: 30,
    fatPerServing: 14,
    ingredientHints: [
      { hint: "Muslo de pollo cocido", gramsPerServing: 180 },
      { hint: "Papa", gramsPerServing: 100 },
    ],
  },
  {
    name: "Arroz con pollo colombiano",
    description: "Arroz amarillo con pollo desmechado y verduras.",
    instructions:
      "1. Cocer pollo y desmechar.\n2. Sofreír arroz con achiote.\n3. Agregar pollo, arvejas, zanahoria.\n4. Cocer hasta secar.",
    prepTimeMin: 15,
    cookTimeMin: 35,
    servings: 3,
    dietTags: ["sin-gluten"],
    allergyTags: [],
    costLevel: 1,
    cuisineCode: "CO",
    caloriesPerServing: 520,
    proteinPerServing: 30,
    carbsPerServing: 60,
    fatPerServing: 14,
    ingredientHints: [
      { hint: "Pechuga de pollo", gramsPerServing: 100 },
      { hint: "Arroz", gramsPerServing: 80 },
    ],
  },
  {
    name: "Fríjoles paisas con arroz",
    description: "Combinación clásica paisa, alta en fibra y proteína.",
    instructions:
      "1. Cocer fríjoles paisas con plátano y especias.\n2. Servir con arroz blanco.",
    prepTimeMin: 10,
    cookTimeMin: 60,
    servings: 3,
    dietTags: ["vegano", "vegetariano", "sin-gluten"],
    allergyTags: [],
    costLevel: 1,
    cuisineCode: "CO",
    caloriesPerServing: 480,
    proteinPerServing: 20,
    carbsPerServing: 80,
    fatPerServing: 6,
    ingredientHints: [
      { hint: "Fríjoles paisas", gramsPerServing: 150 },
      { hint: "Arroz", gramsPerServing: 80 },
    ],
  },
  {
    name: "Patacón con hogao",
    description: "Snack salado típico de la costa colombiana.",
    instructions:
      "1. Cortar plátano verde, freír.\n2. Aplastar y freír de nuevo.\n3. Servir con hogao (sofrito).",
    prepTimeMin: 5,
    cookTimeMin: 15,
    servings: 1,
    dietTags: ["vegano", "vegetariano", "sin-gluten"],
    allergyTags: [],
    costLevel: 1,
    cuisineCode: "CO",
    caloriesPerServing: 320,
    proteinPerServing: 3,
    carbsPerServing: 45,
    fatPerServing: 15,
    ingredientHints: [
      { hint: "Patacón verde", gramsPerServing: 100 },
      { hint: "Hogao", gramsPerServing: 40 },
    ],
  },
  {
    name: "Empanadas de carne (3 unidades)",
    description: "Empanadas fritas rellenas de carne y papa.",
    instructions:
      "1. Preparar relleno: carne molida + papa cocida.\n2. Rellenar la masa.\n3. Freír hasta dorar.",
    prepTimeMin: 20,
    cookTimeMin: 15,
    servings: 1,
    dietTags: [],
    allergyTags: [],
    costLevel: 1,
    cuisineCode: "CO",
    caloriesPerServing: 480,
    proteinPerServing: 18,
    carbsPerServing: 50,
    fatPerServing: 22,
    ingredientHints: [{ hint: "Empanada de carne", gramsPerServing: 210 }],
  },
  {
    name: "Calentado paisa (desayuno)",
    description: "Arroz + fríjoles + huevo del día anterior, calentados con plátano.",
    instructions:
      "1. Calentar fríjoles + arroz del día anterior.\n2. Freír huevo.\n3. Servir con plátano maduro frito.",
    prepTimeMin: 5,
    cookTimeMin: 10,
    servings: 1,
    dietTags: ["vegetariano", "sin-gluten"],
    allergyTags: ["huevo"],
    costLevel: 1,
    cuisineCode: "CO",
    caloriesPerServing: 540,
    proteinPerServing: 22,
    carbsPerServing: 70,
    fatPerServing: 18,
    ingredientHints: [
      { hint: "Fríjoles paisas", gramsPerServing: 100 },
      { hint: "Arroz", gramsPerServing: 80 },
      { hint: "Huevo", gramsPerServing: 50 },
    ],
  },
  {
    name: "Mazamorra con leche",
    description: "Postre/desayuno tradicional paisa.",
    instructions: "1. Servir mazamorra con leche fría y panela rallada.",
    prepTimeMin: 3,
    cookTimeMin: 0,
    servings: 1,
    dietTags: ["vegetariano", "sin-gluten"],
    allergyTags: ["lacteos"],
    costLevel: 1,
    cuisineCode: "CO",
    caloriesPerServing: 280,
    proteinPerServing: 9,
    carbsPerServing: 50,
    fatPerServing: 5,
    ingredientHints: [{ hint: "Mazamorra", gramsPerServing: 200 }],
  },
  {
    name: "Pandebono con café",
    description: "Snack de media mañana ligero.",
    instructions: "1. Calentar pandebono.\n2. Acompañar con café negro.",
    prepTimeMin: 2,
    cookTimeMin: 5,
    servings: 1,
    dietTags: ["vegetariano"],
    allergyTags: ["lacteos", "gluten", "huevo"],
    costLevel: 1,
    cuisineCode: "CO",
    caloriesPerServing: 240,
    proteinPerServing: 8,
    carbsPerServing: 28,
    fatPerServing: 10,
    ingredientHints: [{ hint: "Pandebono", gramsPerServing: 60 }],
  },

  // ─── LATINOAMERICANAS ────────────────────────────────────────────
  {
    name: "Pico de gallo con tacos de pollo",
    description: "Tacos mexicanos con salsa fresca.",
    instructions:
      "1. Cocer y desmechar pollo con especias.\n2. Picar tomate, cebolla, cilantro.\n3. Armar tacos con tortilla.",
    prepTimeMin: 15,
    cookTimeMin: 20,
    servings: 2,
    dietTags: [],
    allergyTags: ["gluten"],
    costLevel: 2,
    cuisineCode: "MX",
    caloriesPerServing: 470,
    proteinPerServing: 35,
    carbsPerServing: 45,
    fatPerServing: 14,
    ingredientHints: [
      { hint: "Pechuga de pollo", gramsPerServing: 120 },
      { hint: "Tomate", gramsPerServing: 60 },
    ],
  },
  {
    name: "Ceviche peruano",
    description: "Pescado blanco fresco en jugo de limón con cebolla.",
    instructions:
      "1. Cortar pescado en cubos.\n2. Marinar con limón 15 min.\n3. Agregar cebolla, ají, cilantro.",
    prepTimeMin: 20,
    cookTimeMin: 0,
    servings: 2,
    dietTags: ["sin-gluten"],
    allergyTags: ["mariscos"],
    costLevel: 3,
    cuisineCode: "PE",
    caloriesPerServing: 280,
    proteinPerServing: 38,
    carbsPerServing: 12,
    fatPerServing: 7,
    ingredientHints: [{ hint: "Pescado", gramsPerServing: 150 }],
  },
  {
    name: "Asado argentino básico",
    description: "Bife a la parrilla con chimichurri.",
    instructions:
      "1. Salar carne 1h antes.\n2. Cocer en parrilla 6-8 min por lado.\n3. Servir con chimichurri.",
    prepTimeMin: 10,
    cookTimeMin: 20,
    servings: 2,
    dietTags: ["keto", "sin-gluten", "paleo"],
    allergyTags: [],
    costLevel: 3,
    cuisineCode: "AR",
    caloriesPerServing: 540,
    proteinPerServing: 45,
    carbsPerServing: 2,
    fatPerServing: 38,
    ingredientHints: [{ hint: "Carne de res", gramsPerServing: 200 }],
  },
  {
    name: "Quinoa con verduras (estilo peruano)",
    description: "Plato vegano alto en proteína vegetal.",
    instructions:
      "1. Cocer quinoa.\n2. Saltear pimentón, zanahoria, brócoli.\n3. Combinar y aderezar.",
    prepTimeMin: 10,
    cookTimeMin: 20,
    servings: 2,
    dietTags: ["vegano", "vegetariano", "sin-gluten"],
    allergyTags: [],
    costLevel: 2,
    cuisineCode: "PE",
    caloriesPerServing: 380,
    proteinPerServing: 14,
    carbsPerServing: 55,
    fatPerServing: 11,
    ingredientHints: [{ hint: "Quinoa", gramsPerServing: 80 }],
  },
  {
    name: "Fajitas de res",
    description: "Tiras de res con pimentón y cebolla en tortilla.",
    instructions:
      "1. Cortar carne en tiras.\n2. Saltear con pimentón y cebolla.\n3. Servir en tortillas con guacamole.",
    prepTimeMin: 15,
    cookTimeMin: 15,
    servings: 2,
    dietTags: [],
    allergyTags: ["gluten"],
    costLevel: 2,
    cuisineCode: "MX",
    caloriesPerServing: 510,
    proteinPerServing: 38,
    carbsPerServing: 40,
    fatPerServing: 22,
    ingredientHints: [{ hint: "Carne de res", gramsPerServing: 150 }],
  },
  {
    name: "Arepa venezolana rellena (reina pepiada)",
    description: "Arepa rellena de pollo con aguacate.",
    instructions:
      "1. Cocer y desmechar pollo.\n2. Mezclar con aguacate y mayonesa.\n3. Rellenar arepa caliente.",
    prepTimeMin: 15,
    cookTimeMin: 15,
    servings: 1,
    dietTags: ["sin-gluten"],
    allergyTags: ["huevo"],
    costLevel: 2,
    cuisineCode: "VE",
    caloriesPerServing: 460,
    proteinPerServing: 28,
    carbsPerServing: 45,
    fatPerServing: 18,
    ingredientHints: [
      { hint: "Arepa", gramsPerServing: 80 },
      { hint: "Pechuga de pollo", gramsPerServing: 80 },
    ],
  },
  {
    name: "Chilaquiles verdes con huevo",
    description: "Desayuno mexicano con totopos en salsa verde.",
    instructions:
      "1. Calentar salsa verde.\n2. Agregar totopos hasta que se ablanden.\n3. Servir con huevo frito.",
    prepTimeMin: 10,
    cookTimeMin: 15,
    servings: 1,
    dietTags: ["vegetariano"],
    allergyTags: ["huevo", "gluten"],
    costLevel: 1,
    cuisineCode: "MX",
    caloriesPerServing: 450,
    proteinPerServing: 18,
    carbsPerServing: 55,
    fatPerServing: 18,
    ingredientHints: [{ hint: "Huevo", gramsPerServing: 100 }],
  },
  {
    name: "Mole con pollo (porción individual)",
    description: "Pollo bañado en salsa de mole oscuro.",
    instructions:
      "1. Cocer pollo.\n2. Calentar pasta de mole con caldo.\n3. Servir el pollo bañado en mole.",
    prepTimeMin: 10,
    cookTimeMin: 30,
    servings: 1,
    dietTags: [],
    allergyTags: ["frutos-secos"],
    costLevel: 2,
    cuisineCode: "MX",
    caloriesPerServing: 510,
    proteinPerServing: 38,
    carbsPerServing: 30,
    fatPerServing: 25,
    ingredientHints: [{ hint: "Pollo", gramsPerServing: 150 }],
  },
  {
    name: "Pastel de choclo (versión ligera)",
    description: "Pastel chileno con maíz dulce y pollo.",
    instructions:
      "1. Sofreír pollo con cebolla.\n2. Cubrir con puré de maíz dulce.\n3. Hornear 25 min.",
    prepTimeMin: 20,
    cookTimeMin: 30,
    servings: 2,
    dietTags: ["vegetariano", "sin-gluten"],
    allergyTags: ["lacteos"],
    costLevel: 2,
    cuisineCode: "CL",
    caloriesPerServing: 430,
    proteinPerServing: 22,
    carbsPerServing: 55,
    fatPerServing: 14,
    ingredientHints: [{ hint: "Maíz", gramsPerServing: 120 }],
  },

  // ─── INTERNACIONALES SALUDABLES ──────────────────────────────────
  {
    name: "Bowl de quinoa con salmón",
    description: "Bowl alto en proteína y omega-3.",
    instructions:
      "1. Cocer quinoa.\n2. Hornear salmón con limón.\n3. Servir con espinaca y aguacate.",
    prepTimeMin: 10,
    cookTimeMin: 25,
    servings: 1,
    dietTags: ["sin-gluten"],
    allergyTags: ["mariscos"],
    costLevel: 3,
    cuisineCode: null,
    caloriesPerServing: 560,
    proteinPerServing: 42,
    carbsPerServing: 35,
    fatPerServing: 28,
    ingredientHints: [
      { hint: "Salmón", gramsPerServing: 150 },
      { hint: "Quinoa", gramsPerServing: 70 },
    ],
  },
  {
    name: "Pollo al horno con espárragos",
    description: "Cena alta en proteína, baja en carbos.",
    instructions:
      "1. Marinar pollo con hierbas.\n2. Hornear 25 min con espárragos.\n3. Servir con limón.",
    prepTimeMin: 10,
    cookTimeMin: 30,
    servings: 1,
    dietTags: ["keto", "sin-gluten", "paleo"],
    allergyTags: [],
    costLevel: 2,
    cuisineCode: null,
    caloriesPerServing: 420,
    proteinPerServing: 45,
    carbsPerServing: 8,
    fatPerServing: 22,
    ingredientHints: [
      { hint: "Pechuga de pollo", gramsPerServing: 180 },
      { hint: "Espárragos", gramsPerServing: 120 },
    ],
  },
  {
    name: "Ensalada César ligera",
    description: "Ensalada clásica con pollo y aderezo bajo en grasa.",
    instructions:
      "1. Cortar lechuga romana.\n2. Agregar pollo a la plancha y crutones (opc).\n3. Aderezar.",
    prepTimeMin: 15,
    cookTimeMin: 10,
    servings: 1,
    dietTags: [],
    allergyTags: ["lacteos", "huevo", "gluten"],
    costLevel: 2,
    cuisineCode: null,
    caloriesPerServing: 380,
    proteinPerServing: 32,
    carbsPerServing: 15,
    fatPerServing: 22,
    ingredientHints: [{ hint: "Pechuga de pollo", gramsPerServing: 120 }],
  },
  {
    name: "Omelet de espinaca con queso",
    description: "Desayuno alto en proteína con vegetales.",
    instructions:
      "1. Batir 3 huevos.\n2. Cocer en sartén con espinaca y queso feta.\n3. Doblar y servir.",
    prepTimeMin: 5,
    cookTimeMin: 8,
    servings: 1,
    dietTags: ["vegetariano", "keto", "sin-gluten"],
    allergyTags: ["huevo", "lacteos"],
    costLevel: 2,
    cuisineCode: null,
    caloriesPerServing: 330,
    proteinPerServing: 24,
    carbsPerServing: 5,
    fatPerServing: 24,
    ingredientHints: [
      { hint: "Huevo", gramsPerServing: 150 },
      { hint: "Espinaca", gramsPerServing: 50 },
    ],
  },
  {
    name: "Tortilla española",
    description: "Tortilla con papa y cebolla, fría o caliente.",
    instructions:
      "1. Freír papa y cebolla en aceite.\n2. Batir huevos, mezclar.\n3. Cocer en sartén, voltear.",
    prepTimeMin: 10,
    cookTimeMin: 20,
    servings: 2,
    dietTags: ["vegetariano", "sin-gluten"],
    allergyTags: ["huevo"],
    costLevel: 1,
    cuisineCode: "ES",
    caloriesPerServing: 380,
    proteinPerServing: 16,
    carbsPerServing: 28,
    fatPerServing: 22,
    ingredientHints: [
      { hint: "Huevo", gramsPerServing: 120 },
      { hint: "Papa", gramsPerServing: 150 },
    ],
  },
  {
    name: "Hummus con vegetales crudos",
    description: "Snack vegano alto en fibra.",
    instructions:
      "1. Servir hummus en bowl.\n2. Acompañar con zanahoria, pepino, apio.",
    prepTimeMin: 5,
    cookTimeMin: 0,
    servings: 1,
    dietTags: ["vegano", "vegetariano"],
    allergyTags: [],
    costLevel: 1,
    cuisineCode: null,
    caloriesPerServing: 250,
    proteinPerServing: 9,
    carbsPerServing: 28,
    fatPerServing: 12,
    ingredientHints: [{ hint: "Garbanzo", gramsPerServing: 80 }],
  },
  {
    name: "Pad Thai vegano",
    description: "Fideos de arroz con tofu y verduras.",
    instructions:
      "1. Hidratar fideos.\n2. Saltear tofu con verduras.\n3. Mezclar con salsa.",
    prepTimeMin: 15,
    cookTimeMin: 15,
    servings: 2,
    dietTags: ["vegano", "vegetariano", "sin-gluten"],
    allergyTags: ["frutos-secos", "soja"],
    costLevel: 2,
    cuisineCode: null,
    caloriesPerServing: 480,
    proteinPerServing: 18,
    carbsPerServing: 65,
    fatPerServing: 16,
    ingredientHints: [{ hint: "Arroz", gramsPerServing: 100 }],
  },
  {
    name: "Salmón al horno con espinaca",
    description: "Cena alta en omega-3 y hierro.",
    instructions:
      "1. Salmón al horno 18 min con limón.\n2. Saltear espinaca con ajo.",
    prepTimeMin: 5,
    cookTimeMin: 20,
    servings: 1,
    dietTags: ["sin-gluten", "keto", "paleo"],
    allergyTags: ["mariscos"],
    costLevel: 3,
    cuisineCode: null,
    caloriesPerServing: 440,
    proteinPerServing: 40,
    carbsPerServing: 5,
    fatPerServing: 28,
    ingredientHints: [{ hint: "Salmón", gramsPerServing: 180 }],
  },
  {
    name: "Bowl mediterráneo (sin pollo)",
    description: "Vegano con falafel, hummus y vegetales.",
    instructions:
      "1. Calentar falafel.\n2. Servir con hummus, tabule, vegetales.",
    prepTimeMin: 10,
    cookTimeMin: 10,
    servings: 1,
    dietTags: ["vegano", "vegetariano"],
    allergyTags: ["gluten"],
    costLevel: 2,
    cuisineCode: null,
    caloriesPerServing: 540,
    proteinPerServing: 20,
    carbsPerServing: 65,
    fatPerServing: 22,
    ingredientHints: [{ hint: "Garbanzo", gramsPerServing: 100 }],
  },
  {
    name: "Pasta integral con pesto y pollo",
    description: "Cena rápida, alta en proteína.",
    instructions:
      "1. Cocer pasta integral 10 min.\n2. Saltear pollo en cubos.\n3. Mezclar con pesto.",
    prepTimeMin: 5,
    cookTimeMin: 15,
    servings: 1,
    dietTags: [],
    allergyTags: ["gluten", "frutos-secos", "lacteos"],
    costLevel: 2,
    cuisineCode: null,
    caloriesPerServing: 520,
    proteinPerServing: 35,
    carbsPerServing: 55,
    fatPerServing: 18,
    ingredientHints: [{ hint: "Pasta", gramsPerServing: 80 }],
  },

  // ─── DESAYUNOS RÁPIDOS ──────────────────────────────────────────
  {
    name: "Avena con frutos rojos",
    description: "Desayuno alto en fibra, listo en 5 min.",
    instructions:
      "1. Hervir agua o leche con avena.\n2. Servir con frutos rojos y nueces.",
    prepTimeMin: 2,
    cookTimeMin: 5,
    servings: 1,
    dietTags: ["vegetariano", "vegano"],
    allergyTags: ["lacteos", "frutos-secos"],
    costLevel: 1,
    cuisineCode: null,
    caloriesPerServing: 320,
    proteinPerServing: 12,
    carbsPerServing: 50,
    fatPerServing: 8,
    ingredientHints: [{ hint: "Avena", gramsPerServing: 50 }],
  },
  {
    name: "Smoothie verde con proteína",
    description: "Bebida fría con espinaca, banana y whey.",
    instructions:
      "1. Licuar espinaca, banana, leche, whey, hielo.\n2. Servir frío.",
    prepTimeMin: 5,
    cookTimeMin: 0,
    servings: 1,
    dietTags: ["vegetariano", "sin-gluten"],
    allergyTags: ["lacteos"],
    costLevel: 2,
    cuisineCode: null,
    caloriesPerServing: 280,
    proteinPerServing: 28,
    carbsPerServing: 25,
    fatPerServing: 6,
    ingredientHints: [
      { hint: "Banano", gramsPerServing: 100 },
      { hint: "Espinaca", gramsPerServing: 30 },
      { hint: "Proteína", gramsPerServing: 30 },
    ],
  },
  {
    name: "Tostadas francesas con miel",
    description: "Pan tostado en huevo y leche.",
    instructions:
      "1. Batir huevo + leche.\n2. Empapar pan y dorar en sartén.\n3. Servir con miel.",
    prepTimeMin: 5,
    cookTimeMin: 5,
    servings: 1,
    dietTags: ["vegetariano"],
    allergyTags: ["huevo", "lacteos", "gluten"],
    costLevel: 1,
    cuisineCode: null,
    caloriesPerServing: 350,
    proteinPerServing: 14,
    carbsPerServing: 45,
    fatPerServing: 13,
    ingredientHints: [{ hint: "Huevo", gramsPerServing: 50 }],
  },
  {
    name: "Yogur con granola y fruta",
    description: "Desayuno rápido sin cocción.",
    instructions:
      "1. Servir yogur en bowl.\n2. Topping con granola y fruta picada.",
    prepTimeMin: 3,
    cookTimeMin: 0,
    servings: 1,
    dietTags: ["vegetariano"],
    allergyTags: ["lacteos", "gluten", "frutos-secos"],
    costLevel: 2,
    cuisineCode: null,
    caloriesPerServing: 310,
    proteinPerServing: 15,
    carbsPerServing: 45,
    fatPerServing: 8,
    ingredientHints: [],
  },
  {
    name: "Huevos revueltos con aguacate",
    description: "Desayuno keto rápido.",
    instructions:
      "1. Revolver 3 huevos con sal.\n2. Servir con medio aguacate en rodajas.",
    prepTimeMin: 3,
    cookTimeMin: 5,
    servings: 1,
    dietTags: ["vegetariano", "keto", "sin-gluten", "paleo"],
    allergyTags: ["huevo"],
    costLevel: 1,
    cuisineCode: null,
    caloriesPerServing: 380,
    proteinPerServing: 20,
    carbsPerServing: 10,
    fatPerServing: 30,
    ingredientHints: [
      { hint: "Huevo", gramsPerServing: 150 },
      { hint: "Aguacate", gramsPerServing: 80 },
    ],
  },
  {
    name: "Pancakes de avena",
    description: "Versión saludable de pancakes, sin azúcar.",
    instructions:
      "1. Mezclar avena, banana, huevo, leche.\n2. Cocer en sartén.\n3. Servir con miel y frutas.",
    prepTimeMin: 5,
    cookTimeMin: 10,
    servings: 1,
    dietTags: ["vegetariano", "sin-gluten"],
    allergyTags: ["huevo", "lacteos"],
    costLevel: 1,
    cuisineCode: null,
    caloriesPerServing: 360,
    proteinPerServing: 18,
    carbsPerServing: 50,
    fatPerServing: 10,
    ingredientHints: [{ hint: "Avena", gramsPerServing: 60 }],
  },
  {
    name: "Café con leche y tostada de aguacate",
    description: "Desayuno simple sin azúcar añadida.",
    instructions:
      "1. Tostar pan integral.\n2. Aplastar aguacate con sal y limón.\n3. Servir con café con leche.",
    prepTimeMin: 5,
    cookTimeMin: 3,
    servings: 1,
    dietTags: ["vegetariano", "vegano"],
    allergyTags: ["gluten", "lacteos"],
    costLevel: 1,
    cuisineCode: null,
    caloriesPerServing: 290,
    proteinPerServing: 10,
    carbsPerServing: 32,
    fatPerServing: 15,
    ingredientHints: [{ hint: "Aguacate", gramsPerServing: 70 }],
  },
  {
    name: "Bowl de chía y frutas",
    description: "Desayuno frío preparado de noche anterior.",
    instructions:
      "1. Mezclar chía con leche, refrigerar 6h.\n2. Servir con fruta y miel.",
    prepTimeMin: 5,
    cookTimeMin: 0,
    servings: 1,
    dietTags: ["vegetariano", "vegano", "sin-gluten"],
    allergyTags: ["lacteos"],
    costLevel: 2,
    cuisineCode: null,
    caloriesPerServing: 280,
    proteinPerServing: 10,
    carbsPerServing: 35,
    fatPerServing: 12,
    ingredientHints: [],
  },
  {
    name: "Sandwich de pavo y queso",
    description: "Almuerzo escolar/oficina rápido.",
    instructions:
      "1. Tostar pan integral.\n2. Armar con pavo, queso, tomate, lechuga.",
    prepTimeMin: 5,
    cookTimeMin: 0,
    servings: 1,
    dietTags: [],
    allergyTags: ["gluten", "lacteos"],
    costLevel: 2,
    cuisineCode: null,
    caloriesPerServing: 420,
    proteinPerServing: 28,
    carbsPerServing: 40,
    fatPerServing: 16,
    ingredientHints: [{ hint: "Pechuga de pavo", gramsPerServing: 80 }],
  },
  {
    name: "Cereal con leche y banana",
    description: "Desayuno clásico ligero.",
    instructions: "1. Servir cereal con leche.\n2. Topping con banana en rodajas.",
    prepTimeMin: 2,
    cookTimeMin: 0,
    servings: 1,
    dietTags: ["vegetariano"],
    allergyTags: ["lacteos", "gluten"],
    costLevel: 1,
    cuisineCode: null,
    caloriesPerServing: 290,
    proteinPerServing: 10,
    carbsPerServing: 55,
    fatPerServing: 5,
    ingredientHints: [{ hint: "Banano", gramsPerServing: 100 }],
  },
  {
    name: "Wrap de pollo y vegetales",
    description: "Almuerzo ligero portátil.",
    instructions:
      "1. Calentar tortilla integral.\n2. Rellenar con pollo, lechuga, tomate, queso.\n3. Enrollar.",
    prepTimeMin: 10,
    cookTimeMin: 5,
    servings: 1,
    dietTags: [],
    allergyTags: ["gluten", "lacteos"],
    costLevel: 2,
    cuisineCode: null,
    caloriesPerServing: 460,
    proteinPerServing: 32,
    carbsPerServing: 45,
    fatPerServing: 16,
    ingredientHints: [{ hint: "Pechuga de pollo", gramsPerServing: 100 }],
  },
];
